# Para esta tarea

Generar un archivo tipo Notebook de Python que contenga el código fuente de varios ejercicios aplicados a los conceptos vistos:
- Uso de librería pandas – leer archivo fifa_eda.csv 
- Visualización de una muestra de 20 líneas. 
- De ser necesario, utilizar el código del ejercicio anterior para no tener que repetir refinamientos de datos
- Generar la media, mínimo y máximo de los jugadores en total, y por país (groupby)
- Generar 2 jugadores ficticios con todos los campos del dataset y añadirlos al mismo.  Visualizarlos con .tail().  Correr nuevamente las estadísticas y compararlas.
- Generar una lambda que añada la zona horaria y la capital del país de nacionalidad
- Generar una lambda que en base al potencial, añada una columna “Candidato” o “Next Year”, para el premio para el balón de oro.  Jugadores con más de 85, son candidatos.

## Uso de librerias

### Importacion

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Lectura del archivo

In [2]:
df = pd.read_csv("../../Archivos-Analisis/files-tarea-m30/fifa_eda.csv")
df

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,238813,J. Lundstram,19,England,47,65,Crewe Alexandra,60.0,1.0,Right,1.0,2.0,CM,2017,2019-01-01,5.750000,134.0,143.0
18203,243165,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,60.0,1.0,Right,1.0,2.0,ST,2018,2020-01-01,6.250000,170.0,113.0
18204,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
18205,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
18206,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0

In [21]:
df.dtypes

ID                            int64
Name                         object
Age                           int64
Nationality                  object
Overall                       int64
Potential                     int64
Club                         object
Value                       float64
Wage                        float64
Preferred Foot               object
International Reputation    float64
Skill Moves                 float64
Position                     object
Joined                        int64
Contract Valid Until         object
Height                      float64
Weight                      float64
Release Clause              float64
dtype: object

In [3]:
df.sample(20)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
13766,206031,Jefté,24,Spain,62,66,SV Mattersburg,400.0,3.0,Right,1.0,2.0,ST,2018,2022-01-01,6.083333,181.0,610.0
7166,223879,L. Ramos,28,Argentina,68,68,Lobos BUAP,925.0,4.0,Right,1.0,3.0,LS,2018,2023-01-01,6.083333,183.0,1500.0
10411,213368,L. Rougeaux,24,France,65,69,KV Kortrijk,575.0,3.0,Right,1.0,2.0,RB,2016,2019-01-01,6.083333,187.0,906.0
8823,207629,J. Villarreal,24,United States,66,71,Orlando City SC,875.0,3.0,Left,1.0,3.0,CF,2018,2022-01-01,5.666667,176.0,1400.0
319,231677,M. Rashford,20,England,81,89,Manchester United,27000.0,110.0,Right,2.0,4.0,LW,2014,2020-01-01,6.083333,154.0,55400.0
117,211117,D. Alli,22,England,84,90,Tottenham Hotspur,42500.0,115.0,Right,3.0,4.0,LCM,2015,2024-01-01,6.166667,176.0,87100.0
5134,139368,J. Shackell,34,England,70,70,Lincoln City,550.0,10.0,Left,1.0,2.0,LCB,2018,2019-01-01,6.333333,183.0,963.0
17255,232679,T. Okuda,29,Japan,55,56,V-Varen Nagasaki,70.0,1.0,Right,1.0,1.0,GK,2016,2018-01-01,6.083333,185.0,93.0
5739,216346,A. Powell,23,Jamaica,69,74,Portland Timbers,1200.0,3.0,Right,1.0,3.0,RB,2013,2019-01-01,6.000000,165.0,1800.0
17955,240272,Min Gyeong Min,22,Korea Republic,51,59,Daegu FC,50.0,1.0,Right,1.0,2.0,CM,2017,2021-01-01,6.000000,143.0,73.0
6731,221473,F. Arancibia,21,Chile,68,80,Universidad de Chile,1600.0,4.0,Left,1.0,3.0,LM,2017,2020-01-01,5.583333,137.0,2600.0
11684,235432,M. Munetsi,22,Zimbabwe,64,71,Orlando Pirates,550.0,1.0,Right,1.0,2.0,CB,2016,2021-01-01,6.166667,183.0,1300.0
5267,214418,S. Ubilla,27,Chile,70,70,Universidad de Chile,1900.0,8.0,Right,1.0,3.0,ST,2018,2019-01-01,5.666667,150.0,2700.0
16103,242587,K. Hattanda,28,Japan,58,58,Nagoya Grampus,130.0,1.0,Right,1.0,2.0,CAM,2017,2018-01-01,5.583333,141.0,163.0
9825,53741,L. Holmes,31,England,66,66,Exeter City,575.0,4.0,Left,1.0,3.0,RM,2015,2019-01-01,5.750000,146.0,1000.0
6426,181971,Huang Bowen,30,China PR,69,69,Guangzhou Evergrande Taobao FC,775.0,8.0,Right,1.0,2.0,CDM,2012,2020-01-01,5.833333,143.0,1700.0
4366,138110,Bruno Alves,36,Portugal,71,71,Parma,325.0,16.0,Right,2.0,3.0,RCB,2018,2019-01-01,6.166667,179.0,585.0
16621,231647,M. Asiri,25,Saudi Arabia,57,60,Al Qadisiyah,90.0,2.0,Right,1.0,1.0,GK,2015,2019-01-01,5.750000,190.0,155.0
6687,176916,G. Abán,31,Argentina,68,68,Unión La Calera,800.0,2.0,Right,1.0,2.0,RW,2017,2021-01-01,5.833333,179.0,1100.0
15662,203192,D. Jarvis,26,Northern Ireland,59,62,Dundalk,160.0,1.0,Left,1.0,2.0,LB,2017,2018-01-01,5.833333,157.0,260.0

## Limpiado de datos

### Identificaicon de valores nulos

In [4]:
df.isnull().sum()

ID                            0
Name                          0
Age                           0
Nationality                   0
Overall                       0
Potential                     0
Club                        241
Value                       252
Wage                          0
Preferred Foot                0
International Reputation     48
Skill Moves                  48
Position                      0
Joined                        0
Contract Valid Until        289
Height                        0
Weight                        0
Release Clause                0
dtype: int64

### Mostrado de los datos nulos

In [5]:
df[df.isnull().any(axis=1)]

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
452,207439,L. Paredes,24,Argentina,80,85,NaN,NaN,0.0,Right,2.0,4.0,CM,2016,NaN,5.916667,165.0,4585.060806
538,156713,A. Granqvist,33,Sweden,80,80,NaN,NaN,0.0,Right,2.0,2.0,LCB,2016,NaN,6.333333,185.0,4585.060806
568,229909,A. Lunev,26,Russia,79,81,NaN,NaN,0.0,Right,1.0,1.0,GK,2016,NaN,6.166667,176.0,4585.060806
677,187347,I. Smolnikov,29,Russia,79,79,NaN,NaN,0.0,Right,2.0,3.0,RB,2016,NaN,5.833333,154.0,4585.060806
864,153260,Hilton,40,Brazil,78,78,Montpellier HSC,NaN,18.0,Right,2.0,3.0,CB,2011,2019-01-01,5.916667,172.0,4585.060806
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17539,234508,C. Singh,21,India,53,62,NaN,NaN,0.0,Right,1.0,2.0,LB,2016,NaN,6.250000,174.0,4585.060806
17672,237744,R. Kawai,39,Japan,53,53,Hokkaido Consadole Sapporo,NaN,1.0,Right,1.0,2.0,CB,2011,2021-01-01,6.000000,165.0,4585.060806
17726,51963,T. Warner,44,Trinidad & Tobago,53,53,Accrington Stanley,NaN,1.0,Right,1.0,1.0,GK,2018,2019-01-01,6.333333,185.0,4585.060806
17752,100899,S. Phillips,40,England,52,52,Yeovil Town,NaN,1.0,Right,1.0,1.0,GK,2017,2022-01-01,6.083333,165.0,4585.060806
18183,53748,K. Pilkington,44,England,48,48,Cambridge United,NaN,1.0,Right,1.0,1.0,GK,2018,2023-01-01,6.166667,190.0,4585.060806

### Eliminado de valores nulos

In [6]:
df.dropna(inplace=True)

In [7]:
# Corroboramos
df.isnull().sum()

ID                          0
Name                        0
Age                         0
Nationality                 0
Overall                     0
Potential                   0
Club                        0
Value                       0
Wage                        0
Preferred Foot              0
International Reputation    0
Skill Moves                 0
Position                    0
Joined                      0
Contract Valid Until        0
Height                      0
Weight                      0
Release Clause              0
dtype: int64

## Media, Minima y Maxima por pais

In [8]:
df_nationality = df.groupby("Nationality")["Overall"].agg(["mean", "min", "max"]).sort_values(by="Nationality", ascending=False)
df_nationality

                  mean  min  max
Nationality
Zimbabwe     69.769231   64   78
Zambia       65.222222   56   73
Wales        64.203125   47   88
Venezuela    67.474576   53   81
Uzbekistan   67.500000   60   75
...                ...  ...  ...
Angola       67.600000   60   78
Andorra      62.000000   62   62
Algeria      70.633333   58   85
Albania      66.025641   52   81
Afghanistan  61.000000   59   63

[163 rows x 3 columns]

## Media, Minima y Maxima por jugador

In [9]:
df_players = df.groupby("Name")["Overall"].agg(["mean", "min", "max"]).sort_values(by="Name", ascending=True)
df_players

                mean  min  max
Name
A. Abang        62.0   62   62
A. Abdellaoui   59.0   59   59
A. Abdennour    73.0   73   73
A. Abdi         69.0   69   69
A. Abdu Jaber   63.0   63   63
...              ...  ...  ...
Óscar Gil       59.0   59   59
Óscar Pinchi    66.0   66   66
Óscar Plano     74.0   74   74
Óscar Valentín  65.0   65   65
Óscar Whalley   65.0   65   65

[16913 rows x 3 columns]

## Merge de 2 jugadores

### Creacion del DF con los dos nuevos jugadores

In [10]:
df_new_players = [(159489, "J, Albaro", 30, "Portugal", 82, 85, "FC Barcelona", 25000, 290, "Right",4,3, "RF",2010, "201-01-01",6.16,183,127100),
                  (45682447, "Mc Miller", 25, "Spain", 92,95,"Real Madrid", 65000,290, "Left",5,5, "RF", 2015,"2026-01-01",5.98,176,250000)]

df_new_players = pd.DataFrame(df_new_players, columns=["ID","Name","Age","Nationality","Overall","Potential","Club","Value","Wage",
                                                       "Preferred Foot","International Reputation","Skill Moves","Position","Joined","Contract Valid Until",
                                                       "Height","Weight","Release Clause"])
df_new_players

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,159489,"J, Albaro",30,Portugal,82,85,FC Barcelona,25000,290,Right,4,3,RF,2010,201-01-01,6.16,183,127100
1,45682447,Mc Miller,25,Spain,92,95,Real Madrid,65000,290,Left,5,5,RF,2015,2026-01-01,5.98,176,250000

### Cambio al tipo de valor igual que el DF principal

In [11]:
df_new_players = df_new_players.astype({'Value': 'float64', 'Wage': 'float64'})

### Concatenacion

In [12]:
df_new = pd.concat([df, df_new_players], axis=0, ignore_index=True)
df_new

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17904,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
17905,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
17906,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0
17907,159489,"J, Albaro",30,Portugal,82,85,FC Barcelona,25000.0,290.0,Right,4.0,3.0,RF,2010,201-01-01,6.160000,183.0,127100.0
17908,45682447,Mc Miller,25,Spain,92,95,Real Madrid,65000.0,290.0,Left,5.0,5.0,RF,2015,2026-01-01,5.980000,176.0,250000.0

### Muestra de los ultimos datos registrados

In [13]:
df_new.tail(5)

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause
17904,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0
17905,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0
17906,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0
17907,159489,"J, Albaro",30,Portugal,82,85,FC Barcelona,25000.0,290.0,Right,4.0,3.0,RF,2010,201-01-01,6.160000,183.0,127100.0
17908,45682447,Mc Miller,25,Spain,92,95,Real Madrid,65000.0,290.0,Left,5.0,5.0,RF,2015,2026-01-01,5.980000,176.0,250000.0

## Media, Minima y Maxima por jugador con nuevo DF

In [14]:
df_new_players = df_new.groupby("Name")["Overall"].agg(["mean","min", "max"]).sort_values(by="Name", ascending=True)
df_new_players

                mean  min  max
Name
A. Abang        62.0   62   62
A. Abdellaoui   59.0   59   59
A. Abdennour    73.0   73   73
A. Abdi         69.0   69   69
A. Abdu Jaber   63.0   63   63
...              ...  ...  ...
Óscar Gil       59.0   59   59
Óscar Pinchi    66.0   66   66
Óscar Plano     74.0   74   74
Óscar Valentín  65.0   65   65
Óscar Whalley   65.0   65   65

[16915 rows x 3 columns]

## Media, Minima y Maxima por pais con nuevo DF

In [15]:
df_new_nat = df_new.groupby("Nationality")["Overall"].agg(["mean", "min", "max"]).sort_values(by="Nationality", ascending=False)
df_new_nat

                  mean  min  max
Nationality
Zimbabwe     69.769231   64   78
Zambia       65.222222   56   73
Wales        64.203125   47   88
Venezuela    67.474576   53   81
Uzbekistan   67.500000   60   75
...                ...  ...  ...
Angola       67.600000   60   78
Andorra      62.000000   62   62
Algeria      70.633333   58   85
Albania      66.025641   52   81
Afghanistan  61.000000   59   63

[163 rows x 3 columns]

españa aumento 1pt en su maxima y .02 en la media

## Zona horaria y capital

### Importacion de libreria

In [ ]:
from countryinfo import CountryInfo

### Copiamos el DF a uno nuevo

In [18]:
df_convert = df_new

Como notas, quisiera mencionar que este proceso es mas complejo que el que se vio en la practica pasada, incluso se utilizo librerias diferenrtes, debido a que las anteriores no se relacionaban de forma correcta con el campo de "Nationality", por lo cual se opto por buscar otras opciones para el trabajo

### Función auxiliar para obtener datos de pais

In [ ]:
# Esta función intentará obtener la Capital y la(s) Zona(s) Horaria(s)
# Usaremos caché para evitar consultas repetidas al objeto CountryInfo
# La función no es la lambda, pero será llamada por la lambda/apply.

# Diccionario de caché para almacenar resultados y evitar recalcular
country_data_cache = {} 

def get_country_details(country_name):
    """
    Intenta obtener la capital y las zonas horarias de un país.
    Utiliza un caché simple para países ya procesados.
    """
    if country_name in country_data_cache:
        return country_data_cache[country_name]
    
    try:
        # Inicializa CountryInfo con el nombre del país
        country = CountryInfo(country_name)
        
        # Obtener la capital. country.capital() devuelve un string.
        capital = country.capital() if country.capital() else 'N/A'
        
        # Obtener las zonas horarias. country.timezones() devuelve una lista.
        # Unimos las zonas horarias en un solo string, separadas por coma.
        timezones = ", ".join(country.timezones()) if country.timezones() else 'N/A'
        
        result = (capital, timezones)
    
    except KeyError:
        # Manejar países que countryinfo no reconoce
        result = ('Country Not Found', 'Country Not Found')
    except Exception:
        # Manejar otros errores
        result = ('Error', 'Error')

    # Almacenar el resultado en el caché antes de devolverlo
    country_data_cache[country_name] = result
    
    return result

# --- 3. Aplicación de la Lamba al DataFrame ---

# La función lambda será la encargada de llamar a la función auxiliar
# y desempaquetar la tupla resultante en las nuevas columnas.

# Aplicamos la función auxiliar a la columna 'Nationality'
# El método .apply() pasa cada valor de la columna a la lambda.
df_convert[['Capital', 'Timezones']] = df_convert['Nationality'].apply(
    lambda x: pd.Series(get_country_details(x))
)

# --- 4. Mostrar el resultado ---

             ID               Name  Age Nationality  Overall  Potential  \
0        158023           L. Messi   31   Argentina       94         94
1         20801  Cristiano Ronaldo   33    Portugal       94         94
2        190871          Neymar Jr   26      Brazil       92         93
3        193080             De Gea   27       Spain       91         93
4        192985       K. De Bruyne   27     Belgium       91         92
...         ...                ...  ...         ...      ...        ...
17904    241638          B. Worman   16     England       47         67
17905    246268     D. Walker-Rice   17     England       47         66
17906    246269          G. Nugent   16     England       46         66
17907    159489          J, Albaro   30    Portugal       82         85
17908  45682447          Mc Miller   25       Spain       92         95

                      Club     Value   Wage Preferred Foot  \
0             FC Barcelona  110500.0  565.0           Left
1                 Juventus   77000.0  405.0          Right
2      Paris Saint-Germain  118500.0  290.0          Right
3        Manchester United   72000.0  260.0          Right
4          Manchester City  102000.0  355.0          Right
...                    ...       ...    ...            ...
17904     Cambridge United      60.0    1.0          Right
17905      Tranmere Rovers      60.0    1.0          Right
17906      Tranmere Rovers      60.0    1.0          Right
17907         FC Barcelona   25000.0  290.0          Right
17908          Real Madrid   65000.0  290.0           Left

       International Reputation  Skill Moves Position  Joined  \
0                           5.0          4.0       RF    2004
1                           5.0          5.0       ST    2018
2                           5.0          5.0       LW    2017
3                           4.0          1.0       GK    2011
4                           4.0          4.0      RCM    2015
...                         ...          ...      ...     ...
17904                       1.0          2.0       ST    2017
17905                       1.0          2.0       RW    2018
17906                       1.0          2.0       CM    2018
17907                       4.0          3.0       RF    2010
17908                       5.0          5.0       RF    2015

      Contract Valid Until    Height  Weight  Release Clause  \
0               2021-01-01  5.583333   159.0        226500.0
1               2022-01-01  6.166667   183.0        127100.0
2               2022-01-01  5.750000   150.0        228100.0
3               2020-01-01  6.333333   168.0        138600.0
4               2023-01-01  5.916667   154.0        196400.0
...                    ...       ...     ...             ...
17904           2021-01-01  5.666667   148.0           165.0
17905           2019-01-01  5.833333   154.0           143.0
17906           2019-01-01  5.833333   176.0           165.0
17907            201-01-01  6.160000   183.0        127100.0
17908           2026-01-01  5.980000   176.0        250000.0

                 Capital                                   Timezones
0           Buenos Aires                                   UTC−03:00
1                 Lisbon                              UTC−01:00, UTC
2               Brasília  UTC−05:00, UTC−04:00, UTC−03:00, UTC−02:00
3                 Madrid                              UTC, UTC+01:00
4               Brussels                                   UTC+01:00
...                  ...                                         ...
17904  Country Not Found                           Country Not Found
17905  Country Not Found                           Country Not Found
17906  Country Not Found                           Country Not Found
17907             Lisbon                              UTC−01:00, UTC
17908             Madrid                              UTC, UTC+01:00

[17909 rows x 20 columns]

### Aplicacion de funcion lambda

In [23]:
df_convert

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,International Reputation,Skill Moves,Position,Joined,Contract Valid Until,Height,Weight,Release Clause,Capital,Timezones
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,110500.0,565.0,Left,5.0,4.0,RF,2004,2021-01-01,5.583333,159.0,226500.0,Buenos Aires,UTC−03:00
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,77000.0,405.0,Right,5.0,5.0,ST,2018,2022-01-01,6.166667,183.0,127100.0,Lisbon,"UTC−01:00, UTC"
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,118500.0,290.0,Right,5.0,5.0,LW,2017,2022-01-01,5.750000,150.0,228100.0,Brasília,"UTC−05:00, UTC−04:00, UTC−03:00, UTC−02:00"
3,193080,De Gea,27,Spain,91,93,Manchester United,72000.0,260.0,Right,4.0,1.0,GK,2011,2020-01-01,6.333333,168.0,138600.0,Madrid,"UTC, UTC+01:00"
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,102000.0,355.0,Right,4.0,4.0,RCM,2015,2023-01-01,5.916667,154.0,196400.0,Brussels,UTC+01:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17904,241638,B. Worman,16,England,47,67,Cambridge United,60.0,1.0,Right,1.0,2.0,ST,2017,2021-01-01,5.666667,148.0,165.0,Country Not Found,Country Not Found
17905,246268,D. Walker-Rice,17,England,47,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,RW,2018,2019-01-01,5.833333,154.0,143.0,Country Not Found,Country Not Found
17906,246269,G. Nugent,16,England,46,66,Tranmere Rovers,60.0,1.0,Right,1.0,2.0,CM,2018,2019-01-01,5.833333,176.0,165.0,Country Not Found,Country Not Found
17907,159489,"J, Albaro",30,Portugal,82,85,FC Barcelona,25000.0,290.0,Right,4.0,3.0,RF,2010,201-01-01,6.160000,183.0,127100.0,Lisbon,"UTC−01:00, UTC"
17908,45682447,Mc Miller,25,Spain,92,95,Real Madrid,65000.0,290.0,Left,5.0,5.0,RF,2015,2026-01-01,5.980000,176.0,250000.0,Madrid,"UTC, UTC+01:00"

In [ ]:
import pytz

In [45]:
df_convert = df_new

In [ ]:
df_convert

In [46]:
df_convert['Nationality'] = df_convert['Nationality'].replace({'England': 'United Kingdom'})

In [ ]:
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo


# Lambda para obtener la capital
get_capital = lambda pais: df_convert.get(pais, {}).get("capital", "Desconocida")

# Lambda para obtener la zona horaria
get_zona = lambda pais: df_convert.get(pais, {}).get("zona_horaria", "UTC")

# Lambda para obtener la hora local según zona horaria
get_hora_local = lambda pais: datetime.now(
    ZoneInfo(df_convert.get(pais, {}).get("zona_horaria", "UTC"))
).strftime("%Y-%m-%d %H:%M:%S")

# Agregar las nuevas columnas al DataFrame
df["capital"] = df["Nationality"].apply(get_capital)
df["zona_horaria"] = df["Nationality"].apply(get_zona)
df["hora_local"] = df["Nationality"].apply(get_hora_local)

# Mostrar algunas filas de ejemplo
print(df[["Name", "Nationality", "capital", "zona_horaria", "hora_local"]].head())

In [19]:
import pandas as pd
from datetime import datetime
from zoneinfo import ZoneInfo

# --- Unir la información ---
# Hacemos un merge (unión) entre ambos DataFrames usando la nacionalidad
df_zh = df_convert.merge(df_convert, how="left", left_on="Nationality", right_on="country")

# --- Añadir columna de hora local con lambda ---
df_zh["hora_local"] = df_zh["timezone"].apply(
    lambda tz: datetime.now(ZoneInfo(tz if pd.notna(tz) else "UTC")).strftime("%Y-%m-%d %H:%M:%S")
)

# --- Selección de columnas relevantes ---
print(df_zh[["Name", "Nationality", "capital", "timezone", "hora_local"]].head())

KeyError: 'country'